# Usa una imagen base de Nginx
FROM nginx:alpine

# Copia los archivos de la página web al directorio donde Nginx sirve los archivos
COPY . /usr/share/nginx/html

# Exponer el puerto 80 para hacer que el contenedor sirva la página web
EXPOSE 80
